name: gradle_showcases
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  geolocator: ^14.0.1
  flutter_app_badger: ^1.5.0
  sample_native_plugin:
    path: ../plugins/sample_native_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true
